config/routes.rb
Rails.application.routes.draw do
  
  resources :feeds
  resources :trades
  devise_for :users
  resources :users
  resources :stores

  namespace :api do
    
    scope :users do
      post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
      delete '/sign_out_mobile',to:'/api/sessions#destroy'
      post '/reset_password',to:'/api/sessions#reset_password'
    end

    post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' } 

    get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

    post '/users/send_message', to: '/api/users#send_message'

    get '/makes',to:'/api/makes#index', defaults: { format: 'json' }

    get '/models',to:'/api/models#index', defaults: { format: 'json' }

    get '/versions',to:'/api/versions#index', defaults: { format: 'json' }

    post '/trades' => 'trades#create'
    delete '/trades' => 'trades#delete'
    get '/trades_matches' => 'trades#trades_matches'
    get '/trades/:id',to:'trades#show', defaults: { format: 'json' }
    get '/matchs' => 'trades#index'
    get '/want_buy' => 'trades#want_buy'
    get '/want_sell' => 'trades#want_sell'
    
    post '/vehicle_images' => 'vehicle_images#create'

  end

  root :to => 'users#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :trade
  belongs_to :user
  belongs_to :store
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    VehicleFipe.get_fipe_data_carro
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:action, :trade_id, :user_id, :store_id)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :trade_id %><br>
    <%= f.text_field :trade_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.text_field :store_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Action</th>
      <th>Trade</th>
      <th>User</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.action %></td>
        <td><%= feed.trade %></td>
        <td><%= feed.user %></td>
        <td><%= feed.store %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @feed.action %>
</p>

<p>
  <strong>Trade:</strong>
  <%= @feed.trade %>
</p>

<p>
  <strong>User:</strong>
  <%= @feed.user %>
</p>

<p>
  <strong>Store:</strong>
  <%= @feed.store %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>