config/routes.rb
Rails.application.routes.draw do
  
  resources :feeds
  resources :trades
  devise_for :users
  resources :users
  resources :stores

  namespace :api do
    
    scope :users do
      post '/sign_in_mobile',to:'/api/sessions#create', defaults: { format: 'json' }
      delete '/sign_out_mobile',to:'/api/sessions#destroy'
      post '/reset_password',to:'/api/sessions#reset_password'
    end

    post '/device_id',to:'/api/device_ids#create', defaults: { format: 'json' } 

    get '/current_user',to:'/api/users#current_user_session', defaults: { format: 'json' }

    post '/users/send_message', to: '/api/users#send_message'

    get '/makes',to:'/api/makes#index', defaults: { format: 'json' }

    get '/models',to:'/api/models#index', defaults: { format: 'json' }

    get '/versions',to:'/api/versions#index', defaults: { format: 'json' }

    post '/trades' => 'trades#create'
    delete '/trades' => 'trades#delete'
    get '/trades_matches' => 'trades#trades_matches'
    get '/trades/:id',to:'trades#show', defaults: { format: 'json' }
    get '/matchs' => 'trades#index'
    get '/want_buy' => 'trades#want_buy'
    get '/want_sell' => 'trades#want_sell'
    
    post '/vehicle_images' => 'vehicle_images#create'

  end

  root :to => 'users#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :users
  belongs_to :plan

  def self.search_store(query)
    joins("JOIN plans ON plan_id = plans.id").where("plans.name like? OR phone like? OR email like? OR stores.name like? OR contact_name like? OR cnpj like? OR address like? OR message like? OR blocked_message like?", "%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%").limit(10).order("name DESC").select('distinct stores.*')
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    respond_to do |format|
      format.html { 
        @stores = Store.order(name: :asc)
      }
      format.js {
        @stores = Store.search_store(params['search'])
        return @stores
      }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :contact_name, :email, :phone, :cnpj, :address, :pay_day, :message, :blocked, :blocked_message, :plan_id)
    end
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :pay_day %><br>
    <%= f.number_field :pay_day %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.label :blocked %><br>
    <%= f.check_box :blocked %>
  </div>
  <div class="field">
    <%= f.label :blocked_message %><br>
    <%= f.text_field :blocked_message %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br>
    <%= f.text_field :plan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/_liststores.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Cnpj</th>
      <th>Address</th>
      <th>Pay day</th>
      <th>Message</th>
      <th>Blocked</th>
      <th>Blocked message</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.contact_name %></td>
        <td><%= store.email %></td>
        <td><%= store.phone %></td>
        <td><%= store.cnpj %></td>
        <td><%= store.address %></td>
        <td><%= store.pay_day %></td>
        <td><%= store.message %></td>
        <td><%= store.blocked %></td>
        <td><%= store.blocked_message %></td>
        <td><%= store.plan %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stores</h1>

<%= form_tag stores_path, :method => 'get', :id => "stores_search", remote: true do %>
    <div> <%= text_field_tag :search, params[:search],:placeholder =>"Pesquisar"%> <br></div>
<% end %>

<div id="stores">
    <%= render 'stores/liststores' %>
</div>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/index.js.erb
$("#stores").replaceWith('<div id="stores"><%= j render :partial => "liststores"%></div>');

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @store.contact_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @store.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @store.cnpj %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Pay day:</strong>
  <%= @store.pay_day %>
</p>

<p>
  <strong>Message:</strong>
  <%= @store.message %>
</p>

<p>
  <strong>Blocked:</strong>
  <%= @store.blocked %>
</p>

<p>
  <strong>Blocked message:</strong>
  <%= @store.blocked_message %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @store.plan %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>